### ISSUE TITLE
specific git branch on https mis-reported as wrong SSH URL

### ISSUE THREAD

**Issue by stain** [common-workflow-language/cwlviewer#153]
If I try http://view.commonwl.org:8082/workflows

with 

* URL: `https://github.com/common-workflow-language/workflows.git`
* Branch: `master`
* Path: `/workflows/compile/compile1.cwl`

Then this should be equivalent to just the URL with `https://github.com/common-workflow-language/workflows/tree/master/workflows/compile/compile1.cwl` - however on the current master branch it fails with:

> Error: SSH URLs are not supported, please provide a HTTPS URL for the repository or submodules

No messages (At all) are logged on server or JS console.

**Comment by stain** [comment]
```
org.eclipse.jgit.api.errors.TransportException: https://github.com/common-workflow-language/workflows.git.git: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:245) ~[org.eclipse.jgit-4.8.0.201706111038-r.jar:4.8.0.201706111038-r]
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:293) ~[org.eclipse.jgit-4.8.0.201706111038-r.jar:4.8.0.201706111038-r]
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:190) ~[org.eclipse.jgit-4.8.0.201706111038-r.jar:4.8.0.201706111038-r]
	at org.commonwl.view.git.GitService.getRepository(GitService.java:105) ~[classes/:na]
```

double git problem
