### ISSUE TITLE
Several unexplained errors

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#193]
## Description
https://github.com/mr-c/mc3/blob/viz/mc3_vcf2maf.cwl
https://github.com/mr-c/mc3/blob/viz/mc3_vcf2maf_full.cwl
https://github.com/mr-c/mc3/blob/viz/mc3_vcf_postfilter.cwl

## Expected Behavior
Detailed error message

## Actual Behavior

> Error: The workflow could not be retrieved from the Git repository using the details given

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, Java 1.8):

**Comment by stain** [comment]
For some reason `cwltool` needs Node.js just to `--validate` or `--print-rdf`, but `node` is not available within the docker image.

```
JavascriptException: cwltool requires Node.js engine to evaluate and validate Javascript expressions, but couldn't find it.  Tried nodejs, node, docker run node:slim
bash-4.4# cwltool --debug --print-rdf https://raw.githubusercontent.com/mr-c/mc3/viz/mc3_vcf2maf.cwl
/usr/bin/cwltool 1.0.20180523203033
I'm sorry, I couldn't load this CWL file.  The error was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cwltool/main.py", line 492, in main
    makeTool, make_tool_kwds)
  File "/usr/lib/python2.7/site-packages/cwltool/load_tool.py", line 341, in make_tool
    tool = makeTool(processobj, **kwargs)
  File "/usr/lib/python2.7/site-packages/cwltool/workflow.py", line 44, in defaultMakeTool
    return Workflow(toolpath_object, **kwargs)
  File "/usr/lib/python2.7/site-packages/cwltool/workflow.py", line 432, in __init__
    self.steps.append(WorkflowStep(step, n, **kwargs))
  File "/usr/lib/python2.7/site-packages/cwltool/workflow.py", line 506, in __init__
    overrides=kwargs.get("overrides"))
  File "/usr/lib/python2.7/site-packages/cwltool/load_tool.py", line 370, in load_tool
    makeTool, kwargs if kwargs else {})
  File "/usr/lib/python2.7/site-packages/cwltool/load_tool.py", line 341, in make_tool
    tool = makeTool(processobj, **kwargs)
  File "/usr/lib/python2.7/site-packages/cwltool/workflow.py", line 40, in defaultMakeTool
    return command_line_tool.CommandLineTool(toolpath_object, **kwargs)
  File "/usr/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 200, in __init__
    super(CommandLineTool, self).__init__(toolpath_object, **kwargs)
  File "/usr/lib/python2.7/site-packages/cwltool/process.py", line 546, in __init__
    validate_js_expressions(cast(CommentedMap, toolpath_object), self.doc_schema.names[toolpath_object["class"]], validate_js_options)
  File "/usr/lib/python2.7/site-packages/cwltool/validate_js.py", line 187, in validate_js_expressions
    expression_errors, _ = jshint_js(code_fragment_js, js_globals, jshint_options)
  File "/usr/lib/python2.7/site-packages/cwltool/validate_js.py", line 113, in jshint_js
    context=jshint_functions_text
  File "/usr/lib/python2.7/site-packages/cwltool/sandboxjs.py", line 152, in exec_js_process
    new_proc = new_js_proc(js_engine_code, force_docker_pull=force_docker_pull)
  File "/usr/lib/python2.7/site-packages/cwltool/sandboxjs.py", line 109, in new_js_proc
    u"docker run node:slim" % u", ".join(trynodes))
JavascriptException: cwltool requires Node.js engine to evaluate and validate Javascript expressions, but couldn't find it.  Tried nodejs, node, docker run node:slim
```

**Comment by stain** [comment]
If I do `apk add nodejs` it [works](http://view.commonwl.org:8082/workflows/github.com/mr-c/mc3/blob/viz/mc3_vcf2maf_full.cwl#).. I can add that to the `Dockerfile` - but not sure why it should be needed?
